### ISSUE TITLE
[Feature] Set dark background colour for search and status bar on mobile devices

### ISSUE THREAD

**Issue by olifre** [pages-themes/hacker#67]
Mobile devices using a bright theme visiting a hacker-themed page do not adapt their header / status bar colour to the dark background colour of the hacker theme.

This is possible with the following header tags:
```HTML
<!-- Chrome, Firefox OS and Opera -->
<meta name="theme-color" content="#151515" />
<!-- Windows Phone -->
<meta name="msapplication-navbutton-color" content="#151515" />
<!-- iOS Safari -->
<meta name="apple-mobile-web-app-status-bar-style" content="#151515" />
```
(see also: https://stackoverflow.com/questions/26960703/how-to-change-the-color-of-header-bar-and-address-bar-in-newest-chrome-version-o for screenshots and examples)

**Comment by davorpa** [comment]
Hey @olifre

Nice enhacement.

Since document is HTML5 doctyped, close meta tags are not needed. To maintain same code guidelines on entire template I recommend remove the trailing slash.

The color `#151515` matches with defined for body background...
https://github.com/pages-themes/hacker/blob/7b7303abefd44daf037249f1f9281d46ee1e1a91/_sass/_default_colors.scss#L5
https://github.com/pages-themes/hacker/blob/7b7303abefd44daf037249f1f9281d46ee1e1a91/_sass/jekyll-theme-hacker.scss#L4
... but according to [Safari guidelines](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html#//apple_ref/doc/uid/TP40008193-SW4), an extra meta tag is needed to make the color effective `apple-mobile-web-app-capable` ([What implies enable it?](https://medium.com/@firt/dont-use-ios-web-app-meta-tag-irresponsibly-in-your-progressive-web-apps-85d70f4438cb)). Moreover, the color can only take three values: `default`, `black` and `black-translucent`. With this last, body background color is used to compute status bar color.

Then the snippet looks as some like this:

```
<!-- Chrome, Firefox OS and Opera -->
<meta name="theme-color" content="#151515">
<!-- Windows Phone -->
<meta name="msapplication-navbutton-color" content="#151515">
<!-- iOS Safari -->
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
```

What do you think about?

**Comment by olifre** [comment]
> What do you think about?

That looks like several great improvements, thanks for this research :+1: ! 
Did you already test this with a Safari mobile browser? I don't have access to one, but a test might be worthwhile to check if there are also unintended side-effects from the "capable" meta tag.

**Comment by davorpa** [comment]
> Did you already test this with a Safari mobile browser?

Sorry, me neither, no iPhone 😣

I've been taking a look at some webs, also the other themes and in Caiman was approved with `black-translucent` and **not `-capable`**
https://github.com/pages-themes/cayman/pull/43/commits/fa9637941afa21f1e5b186b894ba83e890b54e9c
![Screenshot_20210629-215258](https://user-images.githubusercontent.com/3125580/123860936-d9250a00-d926-11eb-822e-38e326a50fc2.png)

There are enough top gap how to allow overlap mode, so `black-translucent` it's fine. With `black` it would also look good due to this theme has a quite dark background color.
![Screenshot_20210629-215216](https://user-images.githubusercontent.com/3125580/123861954-0d4cfa80-d928-11eb-8ead-8d707db62dcf.png)

So... both are valid for me.

```
<!-- Chrome, Firefox OS and Opera -->
<meta name="theme-color" content="#151515">
<!-- Windows Phone -->
<meta name="msapplication-navbutton-color" content="#151515">
<!-- iOS Safari -->
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
```

```
<!-- Chrome, Firefox OS and Opera -->
<meta name="theme-color" content="#151515">
<!-- Windows Phone -->
<meta name="msapplication-navbutton-color" content="#151515">
<!-- iOS Safari -->
<meta name="apple-mobile-web-app-status-bar-style" content="black">
```

Fix it as you wish 😉. I review 🤗.

**Comment by olifre** [comment]
I think I'd also expect `black-translucent` to work fine, and not specifying `-capable` seems more safe to me. While this does not match the Safari documentation, the screenshot you found seems to show it works nevertheless, and it seems more safe since it does not change other behaviour :wink:. 
I can also only suggest here, we'll have to wait for someone with commit privileges to review and merge.

**Comment by davorpa** [comment]
Yep.

The screenshots are captured using a Samsung S5 on Chrome.

I hope that any admin approve and release. It seems that theme projects are a bit abandoned.

Meanwhile there will be to wait for Travis CI build
